# -*- coding: UTF-8 -*-

IscoFirstLevelGroup.delete_all
IscoSecondLevelGroup.delete_all
IscoThirdLevelGroup.delete_all
IscoFourthLevelGroup.delete_all

isco_first_level_groups = [
  { code: '1', name: 'Directores y gerentes' },
  { code: '2', name: 'Profesionales científicos e intelectuales' },
  { code: '3', name: 'Técnicos y profesionales de nivel medio' },
  { code: '4', name: 'Personal de apoyo administrativo' },
  { code: '5', name: 'Trabajadores de los servicios y vendedores de comercios y mercados' },
  { code: '6', name: 'Agricultores y trabajadores calificados agropecuarios, forestales y pesqueros' },
  { code: '7', name: 'Oficiales, operarios y artesanos de artes mecánicas y de otros oficios' },
  { code: '8', name: 'Operadores de instalaciones y máquinas y ensambladores' },
  { code: '9', name: 'Ocupaciones elementales' },
  { code: '0', name: 'Ocupaciones militares' }
]
isco_first_level_groups.each do |group|
  IscoFirstLevelGroup.create! code: group[:code], name: group[:name]
end

isco_second_level_groups = [
  { first_level_code: '1', code: '11', name: 'Directores ejecutivos, personal directivo de la administración pública y miembros del poder ejecutivo y de los cuerpos legislativos' },
  { first_level_code: '1', code: '12', name: 'Directores administradores y comerciales' },
  { first_level_code: '1', code: '13', name: 'Directores y gerentes de producción y operaciones' },
  { first_level_code: '1', code: '14', name: 'Gerentes de hoteles, restaurantes, comercios y otros servicios' },
  { first_level_code: '2', code: '21', name: 'Profesionales de las ciencias y de la ingeniería' },
  { first_level_code: '2', code: '22', name: 'Profesionales de la salud' },
  { first_level_code: '2', code: '23', name: 'Profesionales de la enseñanza' },
  { first_level_code: '2', code: '24', name: 'Especialistas en organización de la administración publica y de empresas' },
  { first_level_code: '2', code: '25', name: 'Profesionales de tecnología de la información y las comunicaciones' },
  { first_level_code: '2', code: '26', name: 'Profesionales en derecho, en ciencias sociales y culturales' },
  { first_level_code: '3', code: '31', name: 'Profesionales de las ciencias y la ingeniería de nivel medio' },
  { first_level_code: '3', code: '32', name: 'Profesionales de nivel medio de la salud' },
  { first_level_code: '3', code: '33', name: 'Profesionales de nivel medio en operaciones financieras y administrativas' },
  { first_level_code: '3', code: '34', name: 'Profesionales de nivel medio de servicios jurídicos, sociales, culturales y afines' },
  { first_level_code: '3', code: '35', name: 'Técnicos de la tecnología de la información y las comunicaciones' },
  { first_level_code: '4', code: '41', name: 'Oficinistas' },
  { first_level_code: '4', code: '42', name: 'Empleados en trato directo con el público' },
  { first_level_code: '4', code: '43', name: 'Empleados contables y encargados del registro de materiales' },
  { first_level_code: '4', code: '44', name: 'Otro personal de apoyo administrativo' },
  { first_level_code: '5', code: '51', name: 'Trabajadores de los servicios personales' },
  { first_level_code: '5', code: '52', name: 'Vendedores' },
  { first_level_code: '5', code: '53', name: 'Trabajadores de los cuidados personales' },
  { first_level_code: '5', code: '54', name: 'Personal de los servicios de protección' },
  { first_level_code: '6', code: '61', name: 'Agricultores y trabajadores calificados de explotaciones agropecuarias con destino al mercado' },
  { first_level_code: '6', code: '62', name: 'Trabajadores forestales calificados, pescadores y cazadores' },
  { first_level_code: '6', code: '63', name: 'Trabajadores agropecuarios, pescadores, cazadores y recolectores de subsistencia' },
  { first_level_code: '7', code: '71', name: 'Oficiales y operarios de la construcción excluyendo electricistas' },
  { first_level_code: '7', code: '72', name: 'Oficiales y operarios de la metalurgia, la construcción mecánica y afines' },
  { first_level_code: '7', code: '73', name: 'Artesanos y operarios de las artes gráficas' },
  { first_level_code: '7', code: '74', name: 'Trabajadores especializados en electricidad y la elecrotecnología' },
  { first_level_code: '7', code: '75', name: 'Operarios y oficiales de procesamiento de alimentos, de la confección, ebanistas, otros artesanos y afines' },
  { first_level_code: '8', code: '81', name: 'Operadores de instalaciones fijas y máquinas' },
  { first_level_code: '8', code: '82', name: 'Ensambladores' },
  { first_level_code: '8', code: '83', name: 'Conductores de vehículos y operadores de equipos pesados móviles' },
  { first_level_code: '9', code: '91', name: 'Limpiadores y asistentes' },
  { first_level_code: '9', code: '92', name: 'Peones agropecuarios, pesqueros y forestales' },
  { first_level_code: '9', code: '93', name: 'Peones de la minería, la construcción, la industria manufacturera y el transporte' },
  { first_level_code: '9', code: '94', name: 'Ayudantes de preparación de alimentos' },
  { first_level_code: '9', code: '95', name: 'Vendedores ambulantes de servicios y afines' },
  { first_level_code: '9', code: '96', name: 'Recolectores de desechos y otras ocupaciones elementales' },
  { first_level_code: '0', code: '01', name: 'Oficiales de las fuerzas armadas' },
  { first_level_code: '0', code: '02', name: 'Suboficiales de las fuerzas armadas' },
  { first_level_code: '0', code: '03', name: 'Otros miembros de las fuerzas armadas' }
]
isco_second_level_groups.each do |group|
  IscoFirstLevelGroup.find_by_code(group[:first_level_code]).isco_second_level_groups.create! code: group[:code], name: group[:name]
end

isco_third_level_groups = [
  { second_level_code: '11', code: '111',	name: 'Miembros del poder ejecutivo y de los cuerpos legislativos' },
  { second_level_code: '11', code: '112',	name: 'Directores generales y gerentes generales' },
  { second_level_code: '12', code: '121',	name: 'Directores de administración y servicios' },
  { second_level_code: '12', code: '122',	name: 'Directores de ventas, comercialización y desarrollo' },
  { second_level_code: '13', code: '131',	name: 'Directores de producción agropecuaria, silvicultura y pesca' },
  { second_level_code: '13', code: '132',	name: 'Directores de industrias manufactureras, de minería, construcción y distribución' },
  { second_level_code: '13', code: '133',	name: 'Directores de servicios de tecnología de la información y las comunicaciones' },
  { second_level_code: '13', code: '134',	name: 'Directores  y gerentes de servicios profesionales' },
  { second_level_code: '14', code: '141',	name: 'Gerentes de hoteles y restaurantes' },
  { second_level_code: '14', code: '142',	name: 'Gerentes de comercios al por mayor y al por menor' },
  { second_level_code: '14', code: '143',	name: 'Otros gerentes de servicios' },
  { second_level_code: '21', code: '211',	name: 'Físicos, químicos y afines' },
  { second_level_code: '21', code: '212',	name: 'Matemáticos, actuarios y estadísticos' },
  { second_level_code: '21', code: '213',	name: 'Profesionales en ciencias biológicas' },
  { second_level_code: '21', code: '214',	name: 'Ingenieros (excluyendo electrotecnólogos)' },
  { second_level_code: '21', code: '215',	name: 'Ingenieros en electrotecnología' },
  { second_level_code: '21', code: '216',	name: 'Arquitectos, urbanistas, agrimensores y diseñadores' },
  { second_level_code: '22', code: '221',	name: 'Médicos' },
  { second_level_code: '22', code: '222',	name: 'Profesionales de enfermería y partería' },
  { second_level_code: '22', code: '223',	name: 'Profesionales de medicina tradicional y alternativa' },
  { second_level_code: '22', code: '224',	name: 'Practicantes paramédicos' },
  { second_level_code: '22', code: '225',	name: 'Veterinarios' },
  { second_level_code: '22', code: '226',	name: 'Otros profesionales de la salud' },
  { second_level_code: '23', code: '231',	name: 'Profesores de universidades y de la enseñanza superior' },
  { second_level_code: '23', code: '232',	name: 'Profesores de formación profesional' },
  { second_level_code: '23', code: '233',	name: 'Profesores de enseñanza secundaria' },
  { second_level_code: '23', code: '234',	name: 'Maestros de enseñanza primaria y maestros preescolares' },
  { second_level_code: '23', code: '235',	name: 'Otros profesionales de la enseñanza' },
  { second_level_code: '24', code: '241',	name: 'Especialistas en finanzas' },
  { second_level_code: '24', code: '242',	name: 'Especialistas en organización de administración' },
  { second_level_code: '24', code: '243',	name: 'Profesionales de las ventas, la comercialización y las relaciones públicas' },
  { second_level_code: '25', code: '251',	name: 'Desarrolladores y analistas de software y multimedia' },
  { second_level_code: '25', code: '252',	name: 'Especialistas en bases de datos y en redes de computadores' },
  { second_level_code: '26', code: '261',	name: 'Profesionales en derecho' },
  { second_level_code: '26', code: '262',	name: 'Archivistas, bibliotecarios, curadores y afines' },
  { second_level_code: '26', code: '263',	name: 'Especialistas en ciencias sociales y teología' },
  { second_level_code: '26', code: '264',	name: 'Autores, periodistas y lingüistas' },
  { second_level_code: '26', code: '265',	name: 'Artistas creativos e interpretativos' },
  { second_level_code: '31', code: '311',	name: 'Técnicos en ciencias físicas y en ingeniería' },
  { second_level_code: '31', code: '312',	name: 'Supervisores en ingeniería de minas, de industrias manufactureras y de la construcción' },
  { second_level_code: '31', code: '313',	name: 'Técnicos en control de procesos' },
  { second_level_code: '31', code: '314',	name: 'Técnicos y profesionales de nivel medio en ciencias biológicas y afines' },
  { second_level_code: '31', code: '315',	name: 'Técnicos y controladores en navegación marítima y aeronáutica' },
  { second_level_code: '32', code: '321',	name: 'Técnicos médicos y farmacéuticos' },
  { second_level_code: '32', code: '322',	name: 'Profesionales de nivel medio de enfermería y partería' },
  { second_level_code: '32', code: '323',	name: 'Profesionales de nivel medio de medicina tradicional y alternativa' },
  { second_level_code: '32', code: '324',	name: 'Técnicos y asistentes veterinarios' },
  { second_level_code: '32', code: '325',	name: 'Otros profesionales de nivel medio de la salud' },
  { second_level_code: '33', code: '331',	name: 'Profesionales de nivel medio en finanzas y matemáticas' },
  { second_level_code: '33', code: '332',	name: 'Agentes comerciales y corredores' },
  { second_level_code: '33', code: '333',	name: 'Agentes de servicios comerciales' },
  { second_level_code: '33', code: '334',	name: 'Secretarios administrativos y especializados' },
  { second_level_code: '33', code: '335',	name: 'Agentes de la administración pública para la aplicación de la ley y afines' },
  { second_level_code: '34', code: '341',	name: 'Profesionales de nivel medio, de servicios jurídicos, sociales y religiosos' },
  { second_level_code: '34', code: '342',	name: 'Entrenadores de deportes y aptitud física' },
  { second_level_code: '34', code: '343',	name: 'Profesionales de nivel medio en actividades culturales, artísticas y culinarias' },
  { second_level_code: '35', code: '351',	name: 'Técnicos en operaciones de tecnología de la información y las comunicaciones y asistencia al usuario' },
  { second_level_code: '35', code: '352',	name: 'Técnicos en telecomunicaciones y radiodifusión' },
  { second_level_code: '41', code: '411',	name: 'Oficinistas generales' },
  { second_level_code: '41', code: '412',	name: 'Secretarios (general)' },
  { second_level_code: '41', code: '413',	name: 'Operadores de máquinas de oficina' },
  { second_level_code: '42', code: '421',	name: 'Pagadores y cobradores de ventanilla y afines' },
  { second_level_code: '42', code: '422',	name: 'Empleados de servicios de información al cliente' },
  { second_level_code: '43', code: '431',	name: 'Auxiliares contables y financieros' },
  { second_level_code: '43', code: '432',	name: 'Empleados encargados del registro de materiales y de transportes' },
  { second_level_code: '44', code: '441',	name: 'Otro personal de apoyo administrativo' },
  { second_level_code: '51', code: '511',	name: 'Personal al servicio directo de los pasajeros' },
  { second_level_code: '51', code: '512',	name: 'Cocineros' },
  { second_level_code: '51', code: '513',	name: 'Camareros' },
  { second_level_code: '51', code: '514',	name: 'Peluqueros, especialistas en tratamientos de belleza y afines' },
  { second_level_code: '51', code: '515',	name: 'Supervisores de mantenimiento y limpieza de edificios' },
  { second_level_code: '51', code: '516',	name: 'Otros trabajadores de servicios personales' },
  { second_level_code: '52', code: '521',	name: 'Vendedores callejeros y de puestos de mercado' },
  { second_level_code: '52', code: '522',	name: 'Comerciantes y vendedores de tiendas y almacenes' },
  { second_level_code: '52', code: '523',	name: 'Cajeros y expendedores de billetes' },
  { second_level_code: '52', code: '524',	name: 'Otros vendedores' },
  { second_level_code: '53', code: '531',	name: 'Cuidadores de niños y auxiliares de maestros' },
  { second_level_code: '53', code: '532',	name: 'Trabajadores de los cuidados personales en servicios de salud' },
  { second_level_code: '54', code: '541',	name: 'Personal de los servicios de protección' },
  { second_level_code: '61', code: '611',	name: 'Agricultores y trabajadores calificados de jardines y de cultivos para el mercado' },
  { second_level_code: '61', code: '612',	name: 'Criadores y trabajadores pecuarios calificados de la cría de animales para el mercado y afines' },
  { second_level_code: '61', code: '613',	name: 'Productores y trabajadores calificados de explotaciones agropecuarias mixtas cuya producción se destina al mercado' },
  { second_level_code: '62', code: '621',	name: 'Trabajadores forestales calificados y afines' },
  { second_level_code: '62', code: '622',	name: 'Pescadores, cazadores y tramperos' },
  { second_level_code: '63', code: '631',	name: 'Trabajadores agrícolas de subsistencia' },
  { second_level_code: '63', code: '632',	name: 'Trabajadores pecuarios de subsistencia' },
  { second_level_code: '63', code: '633',	name: 'Trabajadores agropecuarios de subsistencia' },
  { second_level_code: '63', code: '634',	name: 'Pescadores, cazadores, tramperos y recolectores de subsistencia' },
  { second_level_code: '71', code: '711',	name: 'Oficiales y operarios de la construcción (obra gruesa) y afines' },
  { second_level_code: '71', code: '712',	name: 'Oficiales y operarios de la construcción (trabajos de acabado) y afines' },
  { second_level_code: '71', code: '713',	name: 'Pintores, limpiadores de fachadas y afines' },
  { second_level_code: '72', code: '721',	name: 'Moldeadores, soldadores, chapistas, caldereros, montadores de estructuras metálicas y afines' },
  { second_level_code: '72', code: '722',	name: 'Herreros, herramentistas y afines' },
  { second_level_code: '72', code: '723',	name: 'Mecánicos y reparadores de máquinas' },
  { second_level_code: '73', code: '731',	name: 'Artesanos' },
  { second_level_code: '73', code: '732',	name: 'Oficiales y operarios de las artes gráficas' },
  { second_level_code: '74', code: '741',	name: 'Instaladores y reparadores de equipos eléctricos' },
  { second_level_code: '74', code: '742',	name: 'Instaladores y reparadores de equipos electrónicos y de telecomunicaciones' },
  { second_level_code: '75', code: '751',	name: 'Oficiales y operarios de procesamiento de alimentos y afines' },
  { second_level_code: '75', code: '752',	name: 'Oficiales y operarios del tratamiento de la madera, ebanistas y afines' },
  { second_level_code: '75', code: '753',	name: 'Oficiales y operarios de la confección y afines' },
  { second_level_code: '75', code: '754',	name: 'Otros oficiales, operarios y artesanos de artes mecánicas y de otros oficios' },
  { second_level_code: '81', code: '811',	name: 'Operadores de instalaciones mineras y de extracción y procesamiento de minerales' },
  { second_level_code: '81', code: '812',	name: 'Operadores de instalaciones de procesamiento y recubridoras de metales' },
  { second_level_code: '81', code: '813',	name: 'Operadores de instalaciones y máquinas de productos químicos y fotográficos' },
  { second_level_code: '81', code: '814',	name: 'Operadores de máquinas para fabricar productos de caucho, de papel y de material plástico' },
  { second_level_code: '81', code: '815',	name: 'Operadores de máquinas para fabricar productos textiles y artículos de piel y cuero' },
  { second_level_code: '81', code: '816',	name: 'Operadores de máquinas para elaborar alimentos y productos afines' },
  { second_level_code: '81', code: '817',	name: 'Operadores de instalaciones para la preparación de papel y de procesamiento de la madera' },
  { second_level_code: '81', code: '818',	name: 'Otros operadores de máquinas y de instalaciones fijas' },
  { second_level_code: '82', code: '821',	name: 'Ensambladores' },
  { second_level_code: '83', code: '831',	name: 'Maquinistas de locomotoras y afines' },
  { second_level_code: '83', code: '832',	name: 'Conductores de automóviles, camionetas y motocicletas' },
  { second_level_code: '83', code: '833',	name: 'Conductores de camiones pesados y autobuses' },
  { second_level_code: '83', code: '834',	name: 'Operadores de equipos pesados móviles' },
  { second_level_code: '83', code: '835',	name: 'Marineros de cubierta y afines' },
  { second_level_code: '91', code: '911',	name: 'Limpiadores y asistentes domésticos de hoteles y oficinas' },
  { second_level_code: '91', code: '912',	name: 'Limpiadores de vehículos, ventanas, ropa y otra limpieza a mano' },
  { second_level_code: '92', code: '921',	name: 'Peones agropecuarios, pesqueros y forestales' },
  { second_level_code: '93', code: '931',	name: 'Peones de la minería y la construcción' },
  { second_level_code: '93', code: '932',	name: 'Peones de la industria manufacturera' },
  { second_level_code: '93', code: '933',	name: 'Peones del transporte y almacenamiento' },
  { second_level_code: '94', code: '941',	name: 'Ayudantes de preparación de alimentos' },
  { second_level_code: '95', code: '951',	name: 'Trabajadores ambulantes de servicios y afines' },
  { second_level_code: '95', code: '952',	name: 'Vendedores ambulantes (excluyendo de comida)' },
  { second_level_code: '96', code: '961',	name: 'Recolectores de desechos' },
  { second_level_code: '96', code: '962',	name: 'Otras ocupaciones elementales' },
  { second_level_code: '01', code: '011',	name: 'Oficiales de las fuerzas armadas' },
  { second_level_code: '02', code: '021',	name: 'Suboficiales de las fuerzas armadas' },
  { second_level_code: '03', code: '031',	name: 'Otros miembros de las fuerzas armadas' }
]
isco_third_level_groups.each do |group|
  IscoSecondLevelGroup.find_by_code(group[:second_level_code]).isco_third_level_groups.create! code: group[:code], name: group[:name]
end

isco_fourth_level_groups = [
  { third_level_code: '111', code: '1111', name: 'Miembros del poder legislativo' },
  { third_level_code: '111', code: '1112', name: 'Personal directivo de la administración pública' },
  { third_level_code: '111', code: '1113', name: 'Jefes de pequeñas poblaciones' },
  { third_level_code: '111', code: '1114', name: 'Dirigentes de organizaciones que presentan un interés especial' },
  { third_level_code: '112', code: '1120', name: 'Directores generales y gerentes generales' },
  { third_level_code: '121', code: '1211', name: 'Directores financieros' },
  { third_level_code: '121', code: '1212', name: 'Directores de recursos humanos' },
  { third_level_code: '121', code: '1213', name: 'Directores de políticas y planificación' },
  { third_level_code: '121', code: '1219', name: 'Directores de administración y servicios no clasificados bajo otros epígrafes' },
  { third_level_code: '122', code: '1221', name: 'Directores de ventas y comercialización' },
  { third_level_code: '122', code: '1222', name: 'Directores de publicidad y relaciones públicas' },
  { third_level_code: '122', code: '1223', name: 'Directores de investigación y desarrollo' },
  { third_level_code: '131', code: '1311', name: 'Directores de producción agropecuaria y silvicultura' },
  { third_level_code: '131', code: '1312', name: 'Directores de producción de piscicultura y pesca' },
  { third_level_code: '132', code: '1321', name: 'Directores de industrias manufactureras' },
  { third_level_code: '132', code: '1322', name: 'Directores de explotaciones de minería' },
  { third_level_code: '132', code: '1323', name: 'Directores de empresas de construcción' },
  { third_level_code: '132', code: '1324', name: 'Directores de empresas de abastecimiento, distribución y afines' },
  { third_level_code: '133', code: '1330', name: 'Directores de servicios de tecnología de la información y las comunicaciones' },
  { third_level_code: '134', code: '1341', name: 'Directores de servicios de cuidados infantiles' },
  { third_level_code: '134', code: '1342', name: 'Directores de servicios de salud' },
  { third_level_code: '134', code: '1343', name: 'Directores de servicios de cuidado de las personas de edad' },
  { third_level_code: '134', code: '1344', name: 'Directores  de servicios de bienestar social' },
  { third_level_code: '134', code: '1345', name: 'Directores de servicios de educación' },
  { third_level_code: '134', code: '1346', name: 'Gerentes de sucursales de bancos, de servicios financieros y de seguros' },
  { third_level_code: '134', code: '1349', name: 'Directores y gerentes de servicios profesionales no clasificados bajo otros epígrafes' },
  { third_level_code: '141', code: '1411', name: 'Gerentes de hoteles' },
  { third_level_code: '141', code: '1412', name: 'Gerentes de restaurantes' },
  { third_level_code: '142', code: '1420', name: 'Gerentes de comercios al por mayor y al por menor' },
  { third_level_code: '143', code: '1431', name: 'Gerentes de centros deportivos, de esparcimiento y culturales' },
  { third_level_code: '143', code: '1439', name: 'Gerentes de servicios no clasificados bajo otros epígrafes' },
  { third_level_code: '211', code: '2111', name: 'Físicos y astrónomos' },
  { third_level_code: '211', code: '2112', name: 'Meteorólogos' },
  { third_level_code: '211', code: '2113', name: 'Químicos' },
  { third_level_code: '211', code: '2114', name: 'Geólogos y geofísicos' },
  { third_level_code: '213', code: '2120', name: 'Matemáticos, actuarios y estadísticos' },
  { third_level_code: '213', code: '2131', name: 'Biólogos, botánicos, zoólogos y afines' },
  { third_level_code: '213', code: '2132', name: 'Agrónomos y afines' },
  { third_level_code: '213', code: '2133', name: 'Profesionales de la protección medioambiental' },
  { third_level_code: '214', code: '2141', name: 'Ingenieros industriales y de producción' },
  { third_level_code: '214', code: '2142', name: 'Ingenieros civiles' },
  { third_level_code: '214', code: '2143', name: 'Ingenieros medioambientales' },
  { third_level_code: '214', code: '2144', name: 'Ingenieros mecánicos' },
  { third_level_code: '214', code: '2145', name: 'Ingenieros químicos' },
  { third_level_code: '214', code: '2146', name: 'Ingenieros de minas, metalúrgicos y afines' },
  { third_level_code: '214', code: '2149', name: 'Ingenieros no clasificados bajo otros epígrafes' },
  { third_level_code: '215', code: '2151', name: 'Ingenieros electricistas' },
  { third_level_code: '215', code: '2152', name: 'Ingenieros electrónicos' },
  { third_level_code: '215', code: '2153', name: 'Ingenieros en telecomunicaciones' },
  { third_level_code: '216', code: '2161', name: 'Arquitectos' },
  { third_level_code: '216', code: '2162', name: 'Arquitectos paisajistas' },
  { third_level_code: '216', code: '2163', name: 'Diseñadores de productos y de prendas' },
  { third_level_code: '216', code: '2164', name: 'Urbanistas e ingenieros de tránsito' },
  { third_level_code: '216', code: '2165', name: 'Cartógrafos y agrimensores' },
  { third_level_code: '216', code: '2166', name: 'Diseñadores gráficos y multimedia' },
  { third_level_code: '221', code: '2211', name: 'Médicos generales' },
  { third_level_code: '221', code: '2212', name: 'Médicos especialistas' }, 
  { third_level_code: '222', code: '2221', name: 'Profesionales de enfermería' },
  { third_level_code: '222', code: '2222', name: 'Profesionales de partería' },
  { third_level_code: '223', code: '2230', name: 'Profesionales de medicina tradicional y alternativa' },
  { third_level_code: '224', code: '2240', name: 'Practicantes paramédicos' },
  { third_level_code: '225', code: '2250', name: 'Veterinarios' },
  { third_level_code: '226', code: '2261', name: 'Dentistas' },
  { third_level_code: '226', code: '2262', name: 'Farmacéuticos' },
  { third_level_code: '226', code: '2263', name: 'Profesionales de la salud y la higiene laboral y ambiental' },
  { third_level_code: '226', code: '2264', name: 'Fisioterapeutas' },
  { third_level_code: '226', code: '2265', name: 'Dietistas y nutricionistas' },
  { third_level_code: '226', code: '2266', name: 'Audiólogos y logopedas' },
  { third_level_code: '226', code: '2267', name: 'Optometristas' },
  { third_level_code: '226', code: '2269', name: 'Profesionales de la salud no clasificados bajo otros epígrafes' },
  { third_level_code: '231', code: '2310', name: 'Profesores de universidades y de la enseñanza superior' },
  { third_level_code: '232', code: '2320', name: 'Profesores de formación profesional' },
  { third_level_code: '233', code: '2330', name: 'Profesores de enseñanza secundaria' },
  { third_level_code: '234', code: '2341', name: 'Maestros de enseñanza primaria' },
  { third_level_code: '234', code: '2342', name: 'Maestros preescolares' },
  { third_level_code: '235', code: '2351', name: 'Especialistas en métodos pedagógicos' },
  { third_level_code: '235', code: '2352', name: 'Educadores para necesidades especiales' },
  { third_level_code: '235', code: '2353', name: 'Otros profesores de idiomas' },
  { third_level_code: '235', code: '2354', name: 'Otros profesores de música' },
  { third_level_code: '235', code: '2355', name: 'Otros profesores de artes' },
  { third_level_code: '235', code: '2356', name: 'Instructores en tecnología de la información' },
  { third_level_code: '235', code: '2359', name: 'Profesionales de la enseñanza no clasificados bajo otros epígrafes' },
  { third_level_code: '241', code: '2411', name: 'Contables' },
  { third_level_code: '241', code: '2412', name: 'Asesores financieros y en inversiones' },
  { third_level_code: '241', code: '2413', name: 'Analistas financieros' },
  { third_level_code: '242', code: '2421', name: 'Analistas de gestión y organización' },
  { third_level_code: '242', code: '2422', name: 'Especialistas en políticas de administración' },
  { third_level_code: '242', code: '2423', name: 'Especialistas en políticas y servicios de personal y afines' },
  { third_level_code: '242', code: '2424', name: 'Especialistas en formación del personal' },
  { third_level_code: '243', code: '2431', name: 'Profesionales de la publicidad y la comercialización' },
  { third_level_code: '243', code: '2432', name: 'Profesionales de relaciones públicas' },
  { third_level_code: '243', code: '2433', name: 'Profesionales de ventas técnicas y médicas (excluyendo la TIC)' },
  { third_level_code: '243', code: '2434', name: 'Profesionales de ventas de tecnología de la información y las comunicaciones' },
  { third_level_code: '251', code: '2511', name: 'Analistas de sistemas' },
  { third_level_code: '251', code: '2512', name: 'Desarrolladores de software' },
  { third_level_code: '251', code: '2513', name: 'Desarrolladores Web y multimedia' },
  { third_level_code: '251', code: '2514', name: 'Programadores de aplicaciones' },
  { third_level_code: '251', code: '2519', name: 'Desarrolladores y analistas de software y multimedia y analistas no clasificados bajo otros epígrafes' },
  { third_level_code: '252', code: '2521', name: 'Diseñadores y administradores de bases de datos' },
  { third_level_code: '252', code: '2522', name: 'Administradores de sistemas' },
  { third_level_code: '252', code: '2523', name: 'Profesionales en redes de computadores' },
  { third_level_code: '252', code: '2529', name: 'Especialistas en bases de datos y en redes de computadores no clasificados bajo otros epígrafes' },
  { third_level_code: '261', code: '2611', name: 'Abogados' },
  { third_level_code: '261', code: '2612', name: 'Jueces' },
  { third_level_code: '261', code: '2619', name: 'Profesionales en derecho no clasificados bajo otros epígrafes' },
  { third_level_code: '262', code: '2621', name: 'Archivistas y curadores de museos' },
  { third_level_code: '262', code: '2622', name: 'Bibliotecarios, documentalistas y afines' },
  { third_level_code: '263', code: '2631', name: 'Economistas' },
  { third_level_code: '263', code: '2632', name: 'Sociólogos, antropólogos y afines' },
  { third_level_code: '263', code: '2633', name: 'Filósofos, historiadores y especialistas en ciencias políticas' },
  { third_level_code: '263', code: '2634', name: 'Psicólogos' },
  { third_level_code: '263', code: '2635', name: 'Profesionales del trabajo social' },
  { third_level_code: '263', code: '2636', name: 'Profesionales religiosos' },
  { third_level_code: '264', code: '2641', name: 'Autores y otros escritores' },
  { third_level_code: '264', code: '2642', name: 'Periodistas' },
  { third_level_code: '264', code: '2643', name: 'Traductores, intérpretes y lingüistas' },
  { third_level_code: '265', code: '2651', name: 'Artistas de artes plásticas' },
  { third_level_code: '265', code: '2652', name: 'Músicos, cantantes y compositores' },
  { third_level_code: '265', code: '2653', name: 'Bailarines y coreógrafos' },
  { third_level_code: '265', code: '2654', name: 'Directores de cine, de teatro y afines' },
  { third_level_code: '265', code: '2655', name: 'Actores' },
  { third_level_code: '265', code: '2656', name: 'Locutores de radio, televisión y otros medios de comunicación' },
  { third_level_code: '265', code: '2659', name: 'Artistas creativos e interpretativos no clasificados bajo otros epígrafes' },
  { third_level_code: '311', code: '3111', name: 'Técnicos en ciencias físicas y químicas' },
  { third_level_code: '311', code: '3112', name: 'Técnicos en ingeniería civil' },
  { third_level_code: '311', code: '3113', name: 'Electrotécnicos' },
  { third_level_code: '311', code: '3114', name: 'Técnicos en electrónica' },
  { third_level_code: '311', code: '3115', name: 'Técnicos en ingeniería mecánica' },
  { third_level_code: '311', code: '3116', name: 'Técnicos en química industrial' },
  { third_level_code: '311', code: '3117', name: 'Técnicos en ingeniería de minas y metalurgia' },
  { third_level_code: '311', code: '3118', name: 'Delineantes y dibujantes técnicos' },
  { third_level_code: '311', code: '3119', name: 'Técnicos en ciencias físicas y en ingeniería no clasificados bajo otros epígrafes' },
  { third_level_code: '312', code: '3121', name: 'Supervisores en ingeniería de minas' },
  { third_level_code: '312', code: '3122', name: 'Supervisores de industrias manufactureras' },
  { third_level_code: '312', code: '3123', name: 'Supervisores de la construcción' },
  { third_level_code: '313', code: '3131', name: 'Operadores de instalaciones de producción de energía' },
  { third_level_code: '313', code: '3132', name: 'Operadores de incineradores, instalaciones de tratamiento de agua y afines' },
  { third_level_code: '313', code: '3133', name: 'Controladores de instalaciones de procesamiento de productos químicos' },
  { third_level_code: '313', code: '3134', name: 'Operadores de instalaciones de refinación de petróleo y gas natural' },
  { third_level_code: '313', code: '3135', name: 'Controladores de procesos de producción de metales' },
  { third_level_code: '313', code: '3139', name: 'Técnicos en control de procesos no clasificados bajo otros epígrafes' },
  { third_level_code: '314', code: '3141', name: 'Técnicos en ciencias biológicas (excluyendo la medicina)' },
  { third_level_code: '314', code: '3142', name: 'Técnicos agropecuarios' },
  { third_level_code: '314', code: '3143', name: 'Técnicos forestales' },
  { third_level_code: '315', code: '3151', name: 'Oficiales maquinistas en navegación' },
  { third_level_code: '315', code: '3152', name: 'Capitanes, oficiales de cubierta y prácticos' },
  { third_level_code: '315', code: '3153', name: 'Pilotos de aviación y afines' },
  { third_level_code: '315', code: '3154', name: 'Controladores de tráfico aéreo' },
  { third_level_code: '315', code: '3155', name: 'Técnicos en seguridad aeronáutica' },
  { third_level_code: '321', code: '3211', name: 'Técnicos en aparatos de diagnóstico y tratamiento médico' },
  { third_level_code: '321', code: '3212', name: 'Técnicos de laboratorios médicos' },
  { third_level_code: '321', code: '3213', name: 'Técnicos y asistentes farmacéuticos' },
  { third_level_code: '321', code: '3214', name: 'Técnicos de prótesis médicas y dentales' },
  { third_level_code: '322', code: '3221', name: 'Profesionales de nivel medio de enfermería' },
  { third_level_code: '322', code: '3222', name: 'Profesionales de nivel medio de partería' },
  { third_level_code: '323', code: '3230', name: 'Profesionales de nivel medio de medicina tradicional y alternativa' },
  { third_level_code: '324', code: '3240', name: 'Técnicos y asistentes veterinarios' },
  { third_level_code: '325', code: '3251', name: 'Dentistas auxiliares y ayudantes de odontología' },
  { third_level_code: '325', code: '3252', name: 'Técnicos en documentación sanitaria' },
  { third_level_code: '325', code: '3253', name: 'Trabajadores comunitarios de la salud' },
  { third_level_code: '325', code: '3254', name: 'Técnicos en optometría y ópticos' },
  { third_level_code: '325', code: '3255', name: 'Técnicos y asistentes fisioterapeutas' },
  { third_level_code: '325', code: '3256', name: 'Practicantes y asistentes médicos' },
  { third_level_code: '325', code: '3257', name: 'Inspectores de la salud laboral, medioambiental y afines' },
  { third_level_code: '325', code: '3258', name: 'Ayudantes de ambulancias' },
  { third_level_code: '325', code: '3259', name: 'Profesionales de la salud de nivel medio no clasificados bajo otros epígrafes' },
  { third_level_code: '331', code: '3311', name: 'Agentes de bolsa, cambio y otros servicios financieros' },
  { third_level_code: '331', code: '3312', name: 'Oficiales de préstamos y créditos' },
  { third_level_code: '331', code: '3313', name: 'Tenedores de libros' },
  { third_level_code: '331', code: '3314', name: 'Profesionales de nivel medio de servicios estadísticos, matemáticos y afines' },
  { third_level_code: '331', code: '3315', name: 'Tasadores' },
  { third_level_code: '332', code: '3321', name: 'Agentes de seguros' },
  { third_level_code: '332', code: '3322', name: 'Representantes comerciales' },
  { third_level_code: '332', code: '3323', name: 'Agentes de compras' },
  { third_level_code: '332', code: '3324', name: 'Agentes de compras y consignatarios' },
  { third_level_code: '333', code: '3331', name: 'Declarantes o gestores de aduana' },
  { third_level_code: '333', code: '3332', name: 'Organizadores de conferencias y eventos' },
  { third_level_code: '333', code: '3333', name: 'Agentes de empleo y contratistas de mano de obra' },
  { third_level_code: '333', code: '3334', name: 'Agentes inmobiliarios' },
  { third_level_code: '333', code: '3339', name: 'Agentes de servicios comerciales no clasificados bajo otros epígrafes' },
  { third_level_code: '334', code: '3341', name: 'Supervisores de secretaría' },
  { third_level_code: '334', code: '3342', name: 'Secretarios jurídicos' },
  { third_level_code: '334', code: '3343', name: 'Secretarios administrativos y ejecutivos' },
  { third_level_code: '334', code: '3344', name: 'Secretarios médicos' },
  { third_level_code: '335', code: '3351', name: 'Agentes de aduana e inspectores de fronteras' },
  { third_level_code: '335', code: '3352', name: 'Agentes de administración tributaria' },
  { third_level_code: '335', code: '3353', name: 'Agentes de servicios de seguridad social' },
  { third_level_code: '335', code: '3354', name: 'Agentes de servicios de expedición de licencias y permisos' },
  { third_level_code: '335', code: '3355', name: 'Inspectores de policía y detectives' },
  { third_level_code: '335', code: '3359', name: 'Agentes de la administración pública para la aplicacion de la ley y afines no clasificados bajo otros epígrafes' },
  { third_level_code: '341', code: '3411', name: 'Profesionales de nivel medio del derecho y servicios legales y afines' },
  { third_level_code: '341', code: '3412', name: 'Trabajadores y asistentes sociales de nivel medio' },
  { third_level_code: '341', code: '3413', name: 'Auxiliares laicos de las religiones' },
  { third_level_code: '342', code: '3421', name: 'Atletas y deportistas' },
  { third_level_code: '342', code: '3422', name: 'Entrenadores, instructores y árbitros de actividades deportivas' },
  { third_level_code: '342', code: '3423', name: 'Instructores de educación física y actividades recreativas' },
  { third_level_code: '343', code: '3431', name: 'Fotógrafos' },
  { third_level_code: '343', code: '3432', name: 'Diseñadores y decoradores de interior' },
  { third_level_code: '343', code: '3433', name: 'Técnicos en galerías de arte, museos y bibliotecas' },
  { third_level_code: '343', code: '3434', name: 'Chefs' },
  { third_level_code: '343', code: '3435', name: 'Otros profesionales de nivel medio en actividades culturales y artísticas' },
  { third_level_code: '351', code: '3511', name: 'Técnicos en operaciones de tecnología de la información y las comunicaciones' },
  { third_level_code: '351', code: '3512', name: 'Técnicos en asistencia al usuario de tecnología de la información y las comunicaciones' },
  { third_level_code: '351', code: '3513', name: 'Técnicos en redes y sistemas de computadores' },
  { third_level_code: '351', code: '3514', name: 'Técnicos de la Web' },
  { third_level_code: '352', code: '3521', name: 'Técnicos de radiodifusión y grabación audio visual' },
  { third_level_code: '352', code: '3522', name: 'Técnicos de ingeniería de las telecomunicaciones' },
  { third_level_code: '411', code: '4110', name: 'Oficinistas generales' },
  { third_level_code: '412', code: '4120', name: 'Secretarios (general)' },
  { third_level_code: '413', code: '4131', name: 'Operadores de máquinas de procesamiento de texto y mecanógrafos' },
  { third_level_code: '413', code: '4132', name: 'Grabadores de datos' },
  { third_level_code: '421', code: '4211', name: 'Cajeros de bancos y afines' },
  { third_level_code: '421', code: '4212', name: 'Receptores de apuestas y afines' },
  { third_level_code: '421', code: '4213', name: 'Prestamistas' },
  { third_level_code: '421', code: '4214', name: 'Cobradores y afines' },
  { third_level_code: '422', code: '4221', name: 'Empleados de agencias de viajes' },
  { third_level_code: '422', code: '4222', name: 'Empleados de centros de llamadas' },
  { third_level_code: '422', code: '4223', name: 'Telefonistas' },
  { third_level_code: '422', code: '4224', name: 'Recepcionistas de hoteles' },
  { third_level_code: '422', code: '4225', name: 'Empleados de ventanillas de informaciones' },
  { third_level_code: '422', code: '4226', name: 'Recepcionistas (general)' },
  { third_level_code: '422', code: '4227', name: 'Entrevistadores de encuestas y de investigaciones de mercados' },
  { third_level_code: '422', code: '4229', name: 'Empleados de servicios de información al cliente no clasificados bajo otros epígrafes' },
  { third_level_code: '431', code: '4311', name: 'Empleados de contabilidad y cálculo de costos' },
  { third_level_code: '431', code: '4312', name: 'Empleados de servicios estadísticos, financieros y de seguros' },
  { third_level_code: '431', code: '4313', name: 'Empleados encargados de las nóminas' },
  { third_level_code: '432', code: '4321', name: 'Empleados de control de abastecimientos e inventario' },
  { third_level_code: '432', code: '4322', name: 'Empleados de servicios de apoyo a la producción' },
  { third_level_code: '432', code: '4323', name: 'Empleados de servicios de transporte' },
  { third_level_code: '441', code: '4411', name: 'Empleados de bibliotecas' },
  { third_level_code: '441', code: '4412', name: 'Empleados de servicios de correos' },
  { third_level_code: '441', code: '4413', name: 'Codificadores de datos, correctores de pruebas de imprenta y afines' },
  { third_level_code: '441', code: '4414', name: 'Escribientes públicos y afines' },
  { third_level_code: '441', code: '4415', name: 'Empleados de archivos' },
  { third_level_code: '441', code: '4416', name: 'Empleados del servicio de personal' },
  { third_level_code: '441', code: '4419', name: 'Personal de apoyo administrativo no clasificado bajo otros epígrafes' },
  { third_level_code: '511', code: '5111', name: 'Auxiliares de servicio de abordo' },
  { third_level_code: '511', code: '5112', name: 'Revisores y cobradores de los transportes públicos' },
  { third_level_code: '511', code: '5113', name: 'Guías de turismo' },
  { third_level_code: '512', code: '5120', name: 'Cocineros' },
  { third_level_code: '513', code: '5131', name: 'Camareros de mesas' },
  { third_level_code: '513', code: '5132', name: 'Camareros de barra' },
  { third_level_code: '514', code: '5141', name: 'Peluqueros' },
  { third_level_code: '514', code: '5142', name: 'Especialistas en tratamientos de belleza y afines' },
  { third_level_code: '515', code: '5151', name: 'Supervisores de mantenimiento y limpieza en oficinas, hoteles y otros establecimientos' },
  { third_level_code: '515', code: '5152', name: 'Ecónomos y mayordomos domésticos' },
  { third_level_code: '515', code: '5153', name: 'Conserjes' },
  { third_level_code: '516', code: '5161', name: 'Astrólogos, adivinadores y afines' },
  { third_level_code: '516', code: '5162', name: 'Acompañantes y ayudantes de cámara' },
  { third_level_code: '516', code: '5163', name: 'Personal de pompas fúnebres y embalsamadores' },
  { third_level_code: '516', code: '5164', name: 'Cuidadores de animales' },
  { third_level_code: '516', code: '5165', name: 'Instructores de autoescuela' },
  { third_level_code: '516', code: '5169', name: 'Trabajadores de servicios personales no clasificados bajo otros epígrafes' },
  { third_level_code: '521', code: '5211', name: 'Vendedores de quioscos y de puestos de mercado' },
  { third_level_code: '521', code: '5212', name: 'Vendedores ambulantes de productos comestibles' },
  { third_level_code: '522', code: '5221', name: 'Comerciantes de tiendas' },
  { third_level_code: '522', code: '5222', name: 'Supervisores de tiendas y almacenes' },
  { third_level_code: '522', code: '5223', name: 'Asistentes de venta de tiendas y almacenes' },
  { third_level_code: '523', code: '5230', name: 'Cajeros y expendedores de billetes' },
  { third_level_code: '524', code: '5241', name: 'Modelos de moda, arte y publicidad' },
  { third_level_code: '524', code: '5242', name: 'Demostradores de tiendas' },
  { third_level_code: '524', code: '5243', name: 'Vendedores puerta a puerta' },
  { third_level_code: '524', code: '5244', name: 'Vendedores por teléfono' },
  { third_level_code: '524', code: '5245', name: 'Expendedores de gasolineras' },
  { third_level_code: '524', code: '5246', name: 'Vendedores de comidas al mostrador' },
  { third_level_code: '524', code: '5249', name: 'Vendedores no clasificados bajo otros epígrafes' },
  { third_level_code: '531', code: '5311', name: 'Cuidadores de niños' },
  { third_level_code: '531', code: '5312', name: 'Auxiliares de maestros' },
  { third_level_code: '532', code: '5321', name: 'Trabajadores de los cuidados personales en instituciones' },
  { third_level_code: '532', code: '5322', name: 'Trabajadores de los cuidados personales a domicilio' },
  { third_level_code: '532', code: '5329', name: 'Trabajadores de los cuidados personales en servicios de salud no clasificados bajo otros epígrafes' },
  { third_level_code: '541', code: '5411', name: 'Bomberos' },
  { third_level_code: '541', code: '5412', name: 'Policías' },
  { third_level_code: '541', code: '5413', name: 'Guardianes de prisión' },
  { third_level_code: '541', code: '5414', name: 'Guardias de protección' },
  { third_level_code: '541', code: '5419', name: 'Personal de los servicios de protección no clasificados bajo otros epígrafes' },
  { third_level_code: '611', code: '6111', name:	'Agricultores y trabajadores calificados de cultivos extensivos' },
  { third_level_code: '611', code: '6112', name:	'Agricultores y trabajadores calificados de plantaciones de árboles y arbustos' },
  { third_level_code: '611', code: '6113', name:	'Agricultores y trabajadores calificados de huertas, invernaderos, viveros y jardines' },
  { third_level_code: '611', code: '6114', name:	'Agricultores y trabajadores calificados de cultivos mixtos' },
  { third_level_code: '612', code: '6121', name:	'Criadores de ganado' },
  { third_level_code: '612', code: '6122', name:	'Avicultores y trabajadores calificados de la avicultura' },
  { third_level_code: '612', code: '6123', name:	'Apicultores y sericultores y trabajadores calificados de la apicultura y la sericultura' },
  { third_level_code: '612', code: '6129', name:	'Criadores y trabajadores pecuarios calificados de la cría de animales no clasificados bajo otros epígrafes' },
  { third_level_code: '613', code: '6130', name:	'Productores y trabajadores calificados de explotaciones agropecuarias mixtas cuya producción se destina al mercado' },
  { third_level_code: '621', code: '6210', name:	'Trabajadores forestales calificados y afines' },
  { third_level_code: '622', code: '6221', name:	'Trabajadores de explotaciones de acuicultura' },
  { third_level_code: '622', code: '6222', name:	'Pescadores de agua dulce y en aguas costeras' },
  { third_level_code: '622', code: '6223', name:	'Pescadores de alta mar' },
  { third_level_code: '622', code: '6224', name:	'Cazadores y tramperos' },
  { third_level_code: '631', code: '6310', name:	'Trabajadores agrícolas de subsistencia' },
  { third_level_code: '632', code: '6320', name:	'Trabajadores pecuarios de subsistencia' },
  { third_level_code: '633', code: '6330', name:	'Trabajadores agropecuarios de subsistencia' },
  { third_level_code: '634', code: '6340', name:	'Pescadores, cazadores, tramperos y recolectores de subsistencia' },
  { third_level_code: '711', code: '7111', name:	'Constructores de casas' },
  { third_level_code: '711', code: '7112', name:	'Albañiles' },
  { third_level_code: '711', code: '7113', name:	'Mamposteros, tronzadores, labrantes y grabadores de piedra' },
  { third_level_code: '711', code: '7114', name:	'Operarios en cemento armado, enfoscadores y afines' },
  { third_level_code: '711', code: '7115', name:	'Carpinteros de armar y de obra blanca' },
  { third_level_code: '711', code: '7119', name:	'Oficiales y operarios de la construcción (obra gruesa) y afines no clasificados bajo otros epígrafes' },
  { third_level_code: '712', code: '7121', name:	'Techadores' },
  { third_level_code: '712', code: '7122', name:	'Parqueteros y colocadores de suelos' },
  { third_level_code: '712', code: '7123', name:	'Revocadores' },
  { third_level_code: '712', code: '7124', name:	'Instaladores de material aislante y de insonorización' },
  { third_level_code: '712', code: '7125', name:	'Cristaleros' },
  { third_level_code: '712', code: '7126', name:	'Fontaneros e instaladores de tuberías' },
  { third_level_code: '712', code: '7127', name:	'Mecánicos-montadores de instalaciones de refrigeración y climatización' },
  { third_level_code: '713', code: '7131', name:	'Pintores y empapeladores' },
  { third_level_code: '713', code: '7132', name:	'Barnizadores y afines' },
  { third_level_code: '713', code: '7133', name:	'Limpiadores de fachadas y deshollinadores' },
  { third_level_code: '721', code: '7211', name:	'Moldeadores y macheros' },
  { third_level_code: '721', code: '7212', name:	'Soldadores y oxicortadores' },
  { third_level_code: '721', code: '7213', name:	'Chapistas y caldereros' },
  { third_level_code: '721', code: '7214', name:	'Montadores de estructuras metálicas' },
  { third_level_code: '721', code: '7215', name:	'Aparejadores y empalmadores de cables' },
  { third_level_code: '722', code: '7221', name:	'Herreros y forjadores' },
  { third_level_code: '722', code: '7222', name:	'Herramentistas y afines' },
  { third_level_code: '722', code: '7223', name:	'Reguladores y operadores de máquinas herramientas' },
  { third_level_code: '722', code: '7224', name:	'Pulidores de metales y afiladores de herramientas' },
  { third_level_code: '723', code: '7231', name:	'Mecánicos y reparadores de vehículos de motor' },
  { third_level_code: '723', code: '7232', name:	'Mecánicos y reparadores de motores de avión' },
  { third_level_code: '723', code: '7233', name:	'Mecánicos y reparadores de máquinas agrícolas e industriales' },
  { third_level_code: '723', code: '7234', name:	'Reparadores de bicicletas y afines' },
  { third_level_code: '731', code: '7311', name:	'Mecánicos y reparadores de instrumentos de precisión' },
  { third_level_code: '731', code: '7312', name:	'Fabricantes y afinadores de instrumentos musicales' },
  { third_level_code: '731', code: '7313', name:	'Joyeros, orfebres y plateros' },
  { third_level_code: '731', code: '7314', name:	'Alfareros y afines (barro, arcilla y abrasivos)' },
  { third_level_code: '731', code: '7315', name:	'Sopladores, modeladores, laminadores, cortadores y pulidores de vidrio' },
  { third_level_code: '731', code: '7316', name:	'Redactores de carteles, pintores decorativos y grabadores' },
  { third_level_code: '731', code: '7317', name:	'Artesanos en madera, cestería y materiales similares' },
  { third_level_code: '731', code: '7318', name:	'Artesanos de los tejidos, el cuero y materiales similares' },
  { third_level_code: '731', code: '7319', name:	'Artesanos no clasificados bajo otros epígrafes' },
  { third_level_code: '732', code: '7321', name:	'Cajistas, tipógrafos y afines' },
  { third_level_code: '732', code: '7322', name:	'Impresores' },
  { third_level_code: '732', code: '7323', name:	'Encuadernadores y afines' },
  { third_level_code: '741', code: '7411', name:	'Electricistas de obras y afines' },
  { third_level_code: '741', code: '7412', name:	'Mecánicos y ajustadores electricistas' },
  { third_level_code: '741', code: '7413', name:	'Instaladores y reparadores de líneas eléctricas' },
  { third_level_code: '742', code: '7421', name:	'Mecánicos y reparadores en electrónica' },
  { third_level_code: '742', code: '7422', name:	'Instaladores y reparadores en tecnología de la información y las comunicaciones' },
  { third_level_code: '751', code: '7511', name:	'Carniceros, pescaderos y afines' },
  { third_level_code: '751', code: '7512', name:	'Panaderos, pasteleros y confiteros' },
  { third_level_code: '751', code: '7513', name:	'Operarios de la elaboración de productos lácteos' },
  { third_level_code: '751', code: '7514', name:	'Operarios de la conservación de frutas, legumbres, verduras y afines' },
  { third_level_code: '751', code: '7515', name:	'Catadores y clasificadores de alimentos y bebidas' },
  { third_level_code: '751', code: '7516', name:	'Preparadores y elaboradores de tabaco y sus productos' },
  { third_level_code: '752', code: '7521', name:	'Operarios del tratamiento de la madera' },
  { third_level_code: '752', code: '7522', name:	'Ebanistas y afines' },
  { third_level_code: '752', code: '7523', name:	'Reguladores y operadores de máquinas de labrar madera' },
  { third_level_code: '753', code: '7531', name:	'Sastres, modistos, peleteros y sombrereros' },
  { third_level_code: '753', code: '7532', name:	'Patronistas y cortadores de tela y afines' },
  { third_level_code: '753', code: '7533', name:	'Costureros, bordadores y afines' },
  { third_level_code: '753', code: '7534', name:	'Tapiceros, colchoneros y afines' },
  { third_level_code: '753', code: '7535', name:	'Apelambradores, pellejeros y curtidores' },
  { third_level_code: '753', code: '7536', name:	'Zapateros y afines' },
  { third_level_code: '754', code: '7541', name:	'Buzos' },
  { third_level_code: '754', code: '7542', name:	'Dinamiteros y pegadores' },
  { third_level_code: '754', code: '7543', name:	'Clasificadores y probadores de productos (excluyendo alimentos y bebidas)' },
  { third_level_code: '754', code: '7544', name:	'Fumigadores y otros controladores de plagas y malas hierbas' },
  { third_level_code: '754', code: '7549', name:	'Oficiales, operarios y artesanos de artes mecánicas y de otros oficios no clasificados bajo otros epígrafes' },
  { third_level_code: '811', code: '8111', name:	'Mineros y operadores de instalaciones mineras' },
  { third_level_code: '811', code: '8112', name:	'Operadores de instalaciones de procesamiento de minerales y rocas' },
  { third_level_code: '811', code: '8113', name:	'Perforadores y sondistas de pozos y afines' },
  { third_level_code: '811', code: '8114', name:	'Operadores de máquinas para fabricar cemento y otros productos minerales' },
  { third_level_code: '812', code: '8121', name:	'Operadores de instalaciones de procesamiento de metales' },
  { third_level_code: '812', code: '8122', name:	'Operadores de máquinas pulidoras, galvanizadoras y recubridoras de metales' },
  { third_level_code: '813', code: '8131', name:	'Operadores de plantas y máquinas de productos químicos' },
  { third_level_code: '813', code: '8132', name:	'Operadores de máquinas para fabricar productos fotográficos' },
  { third_level_code: '814', code: '8141', name:	'Operadores de máquinas para fabricar productos de caucho' },
  { third_level_code: '814', code: '8142', name:	'Operadores de máquinas para fabricar productos de material plástico' },
  { third_level_code: '814', code: '8143', name:	'Operadores de máquinas para fabricar productos de papel' },
  { third_level_code: '815', code: '8151', name:	'Operadores de máquinas de preparación de fibras, hilado y devanado' },
  { third_level_code: '815', code: '8152', name:	'Operadores de telares y otras máquinas tejedoras' },
  { third_level_code: '815', code: '8153', name:	'Operadores de máquinas de coser' },
  { third_level_code: '815', code: '8154', name:	'Operadores de máquinas de blanqueamiento, teñido y limpieza de tejidos' },
  { third_level_code: '815', code: '8155', name:	'Operadores de máquinas de tratamiento de pieles y cueros' },
  { third_level_code: '815', code: '8156', name:	'Operadores de máquinas para la fabricación de calzado y afines' },
  { third_level_code: '815', code: '8157', name:	'Operadores de máquinas lavarropas' },
  { third_level_code: '815', code: '8159', name:	'Operadores de máquinas para fabricar productos textiles y artículos de piel y cuero no clasificados bajo otros epígrafes' },
  { third_level_code: '816', code: '8160', name:	'Operadores de máquinas para elaborar alimentos y productos afines' },
  { third_level_code: '817', code: '8171', name:	'Operadores de instalaciones para la preparación de pasta para papel y papel' },
  { third_level_code: '817', code: '8172', name:	'Operadores de instalaciones de procesamiento de la madera' },
  { third_level_code: '818', code: '8181', name:	'Operadores de instalaciones de vidriería y cerámica' },
  { third_level_code: '818', code: '8182', name:	'Operadores de máquinas de vapor y calderas' },
  { third_level_code: '818', code: '8183', name:	'Operadores de máquinas de embalaje, embotellamiento y etiquetado' },
  { third_level_code: '818', code: '8189', name:	'Operadores de máquinas y de instalaciones fijas no clasificados bajo otros epígrafes' },
  { third_level_code: '821', code: '8211', name:	'Ensambladores de maquinaria mecánica' },
  { third_level_code: '821', code: '8212', name:	'Ensambladores de equipos eléctricos y electrónicos' },
  { third_level_code: '821', code: '8219', name:	'Ensambladores no clasificados bajo otros epígrafes' },
  { third_level_code: '831', code: '8311', name:	'Maquinistas de locomotoras' },
  { third_level_code: '831', code: '8312', name:	'Guardafrenos, guardagujas y agentes de maniobras' },
  { third_level_code: '832', code: '8321', name:	'Conductores de motocicletas' },
  { third_level_code: '832', code: '8322', name:	'Conductores de automóviles, taxis y camionetas' },
  { third_level_code: '833', code: '8331', name:	'Conductores de autobuses y tranvías' },
  { third_level_code: '833', code: '8332', name:	'Conductores de camiones pesados' },
  { third_level_code: '834', code: '8341', name:	'Operadores de maquinaria agrícola y forestal móvil' },
  { third_level_code: '834', code: '8342', name:	'Operadores de máquinas de movimiento de tierras y afines' },
  { third_level_code: '834', code: '8343', name:	'Operadores de grúas, aparatos elevadores y afines' },
  { third_level_code: '834', code: '8344', name:	'Operadores de autoelevadoras' },
  { third_level_code: '835', code: '8350', name:	'Marineros de cubierta y afines' },
  { third_level_code: '911', code: '9111', name:	'Limpiadores y asistentes domésticos' },
  { third_level_code: '911', code: '9112', name:	'Limpiadores y asistentes de oficinas, hoteles y otros establecimientos' },
  { third_level_code: '912', code: '9121', name:	'Lavanderos y planchadores manuales' },
  { third_level_code: '912', code: '9122', name:	'Lavadores de vehículos' },
  { third_level_code: '912', code: '9123', name:	'Lavadores de ventanas' },
  { third_level_code: '912', code: '9129', name:	'Otro personal de limpieza' },
  { third_level_code: '921', code: '9211', name:	'Peones de explotaciones agrícolas' },
  { third_level_code: '921', code: '9212', name:	'Peones de explotaciones ganaderas' },
  { third_level_code: '921', code: '9213', name:	'Peones de explotaciones de cultivos mixtos y ganaderos' },
  { third_level_code: '921', code: '9214', name:	'Peones de jardinería y horticultura' },
  { third_level_code: '921', code: '9215', name:	'Peones forestales' },
  { third_level_code: '921', code: '9216', name:	'Peones de pesca y acuicultura' },
  { third_level_code: '931', code: '9311', name:	'Peones de minas y canteras' },
  { third_level_code: '931', code: '9312', name:	'Peones de obras públicas y mantenimiento' },
  { third_level_code: '931', code: '9313', name:	'Peones de la construcción de edificios' },
  { third_level_code: '932', code: '9321', name:	'Empacadores manuales' },
  { third_level_code: '932', code: '9329', name:	'Peones de la industria manufacturera no clasificados bajo otros epígrafes' },
  { third_level_code: '933', code: '9331', name:	'Conductores de vehículos accionados a pedal o a brazo' },
  { third_level_code: '933', code: '9332', name:	'Conductores de vehículos y máquinas de tracción animal' },
  { third_level_code: '933', code: '9333', name:	'Peones de carga' },
  { third_level_code: '933', code: '9334', name:	'Reponedores de estanterías' },
  { third_level_code: '941', code: '9411', name:	'Cocineros de comidas rápidas' },
  { third_level_code: '941', code: '9412', name:	'Ayudantes de cocina' },
  { third_level_code: '951', code: '9510', name:	'Trabajadores ambulantes de servicios y afines' },
  { third_level_code: '952', code: '9520', name:	'Vendedores ambulantes (excluyendo de comida)' },
  { third_level_code: '961', code: '9611', name:	'Recolectores de basura y material reciclable' },
  { third_level_code: '961', code: '9612', name:	'Clasificadores de desechos' },
  { third_level_code: '961', code: '9613', name:	'Barrenderos y afines' },
  { third_level_code: '962', code: '9621', name:	'Mensajeros, mandaderos, maleteros y repartidores' },
  { third_level_code: '962', code: '9622', name:	'Personas que realizan trabajos varios' },
  { third_level_code: '962', code: '9623', name:	'Recolectores de dinero en aparatos de venta automática y lectores de medidores' },
  { third_level_code: '962', code: '9624', name:	'Acarreadores de agua y recolectores  de  leña' },
  { third_level_code: '962', code: '9629', name:	'Ocupaciones elementales no clasificadas bajo otros epígrafes' },
  { third_level_code: '011', code: '0110', name:	'Oficiales de las fuerzas armadas' },
  { third_level_code: '021', code: '0210', name:	'Suboficiales de las fuerzas armadas' },
  { third_level_code: '031', code: '0310', name:	'Otros miembros de las fuerzas armadas' },
]
isco_fourth_level_groups.each do |group|
  IscoThirdLevelGroup.find_by_code(group[:third_level_code]).isco_fourth_level_groups.create! code: group[:code], name: group[:name]
end
